### ISSUE TITLE
Read me - product descriptions and warning (draft?)

### ISSUE THREAD

**Issue by emudoteth** [rkalis/liquidefi#3]
liquiDefi is an unaudited project for ETHglobal Hackmoney. 

This product aims to pool users Dai in order the provide funds to our liquidation bot running on the aave platform. Users depositing Dai are minted sharkDai, by holding sharkDai you are exposed to the profits of the liquidation bot in proportion to your percentage of the pool. 

Anyone holding sharkDai can manually call liquidations on any platform using these pooled funds to carry out that function. This is only permissible if the pool will receive more Dai than what was taken out within the same block. 

This Project is unaudited. Intended only for use and demonstration @ethglobal Hackmoney, Proceed only with extreme caution.

**Comment by rkalis** [comment]
Feel free to add a description like this to the GitHub README. We can always iterate on it later.
